### PR TITLE
upgrade to wildFly23

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
@romartin @cristianonicolai  can you please check:
https://github.com/kiegroup/kie-docker-ci/blob/main/kie-docker-ui-webapp/src/main/java/org/kie/dockerui/backend/service/builder/KieArtifactBuilder.java#L34
Are these things better not to change?

**Comment by mareknovotny** [comment]
> @romartin @cristianonicolai can you please check:
> https://github.com/kiegroup/kie-docker-ci/blob/main/kie-docker-ui-webapp/src/main/java/org/kie/dockerui/backend/service/builder/KieArtifactBuilder.java#L34
> Are these things better not to change?

they are certainly outdated

**Review by mareknovotny — CHANGES_REQUESTED** [review]
https://github.com/kiegroup/kie-docker-ci/pull/25/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R32-R34 needs to be upgraded or removed, not sure why they are needed anyway if you take BC war into docker image?

**Review by romartin — APPROVED** [review]
Hey @mareknovotny @mbiarnes 

Thanks for the updates here, I think this PR is good to go now :+1: 

Also as Marek said above, all those classes from the `UI webapp` stuff (eg: `KieArtifactsBuilder`) are out of date anyway, and as far as I rememer those have no direct relationship with version upgrades, it's just about how the KIE-CI (UI) shows the containers, but it's still wildfly, so rather than the version, I think it's ok, we can just "forget" all those classes in this upgrade.

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
